FROM oven/bun AS builder

WORKDIR /app

COPY package*.json bun.lock* ./

RUN bun install

COPY . .

RUN bun run build

# Serve static files
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
