apiVersion: v1
kind: Secret
metadata:
  name: simple-auth-secret
type: Opaque
stringData:
  postgres_username: tanav
  postgres_password: "tanav@123"
  DATABASE_URL: "postgresql://tanav:tanav@123@postgres-service:5432/postgres"
  ACCESS_TOKEN_SECRET: sct
  REFRESH_TOKEN_SECRET: sct
