apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: simple-auth:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: simple-auth-config
            - secretRef:
                name: simple-auth-secret
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
